### ISSUE TITLE
Nullpointer in chroot configuration

### ISSUE THREAD

**Issue by kolbma** [yadifa/yadifa#8]
I ran over a problem in https://www.yadifa.eu/sites/default/files/releases/yadifa-2.4.0-9809.tar.gz

If you enable (by accident) the **chroot** feature and don't set a **chrootpath** in your configuration, **yafidad** is crashing the memory with this basepath rewriting stuff and you'll get some really strange stuff during startup.
E.g. trying to write the PID number to the configfile (overwriting it), because it points randomly to this memory afterwards.

It is e.g. the code in 
https://github.com/yadifa/yadifa/blob/dc5bed2fb8ec204af9b65eeb91934c2c85098cbb/sbin/yadifad/config_main.c#L603

Should be initialized with "/" or the startup should be aborted with an error message about missing chrootpath config.

**Comment by edfeu** [comment]
Dear Sir,

Thank you for reporting this.

The chroot-path defaults to the “/” value.

The issue was identified as an internal misuse of the chroot-managed pid-path.
The pid-file manager was missing an indirection which was ultimately making it look at the yadifa configuration file instead.
The issue has been fixed in the current source and we plan to push the fix on github in a few hours.

Kind regards,

Eric
